networks:
  rs_network:
services:
  db-rs:
    container_name: db-rs
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - rs_network

  backend:
    build: .
    container_name: recommendation_system
    restart: unless-stopped
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - rs_network
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db-rs
