# Generated by Django 5.1.6 on 2025-02-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.FloatField(default=2.5),
        ),
    ]
