# Generated by Django 5.1.6 on 2025-02-07 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="author",
            table="authors",
        ),
        migrations.AlterModelTable(
            name="book",
            table="books",
        ),
        migrations.AlterModelTable(
            name="genre",
            table="genres",
        ),
    ]
